# Generated by Django 4.2.6 on 2024-02-13 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_follower_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=80)),
                ('post_id', models.CharField(max_length=150)),
            ],
        ),
    ]
